### ISSUE TITLE
Custom Fields need to be updated to CMB2

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/tour-operator#333]
### Description
We need to upgrade the custom field vendor library from CMB to CMB2, as well as register the custom fields with the rest API. We will also take the time to remove any additional code not needed for the fields.

### Tasks
- [x] Replace CMB with CMB2
- [x] Find a replacement for the post search field (CMB2 plugin)
- [x] Review the core post types fields and flag items to move to a sidebar panel.
- [x] Fix the itinerary loop fields (make sure they integrate with the WETU fields)
- [x] Fix the rooms loop (make sure they integrate with the WETU fields)
- [ ] Location Fields
- [ ] Post Connection Fields
- [ ] Fix the styling of the "group" meta fields.

### Custom Fields -> Taxonomies
- [ ] Best time to visit
- [ ] Identify if / should the "spoken_languages", "special_interests" "suggested_visitor_types" can be moved to a taxonomy like the "facilities".

### Figma Single Designs Needed
- [ ] Tour
- [ ] Accommodation
- [ ] Destination

**Comment by krugazul** [comment]
The plugin has been updated to use CMB2, all fields have been tested with the core.
