### ISSUE TITLE
WP Dashboard - Welcome Page

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/tour-operator#335]
### Description
We are going to spruce up the welcome page, it will now show all the time, and you will be redirected to the welcome page on activation.  The Welcome page will also serve as the "Dashboard" for the TO plugin, allowing you to navigate to the different post type areas.

### Notes
- Please branch off the [2.0.0 branch](https://github.com/lightspeedwp/tour-operator/tree/update/2.0.0)
- [Welcome Page Template](https://github.com/lightspeedwp/tour-operator/blob/master/includes/partials/welcome.php)

### Tasks
- [ ] Rebuild the Page structure to fit the WordPress Backend  (leave out the screen options and help drop down for now.)
- [ ] Remove the if statement [here](https://github.com/lightspeedwp/tour-operator/blob/master/includes/classes/admin/class-settings.php#L54-L58), so that both the settings page and welcome page are permanently registered.
- [ ] At a Glance Widget

### Designs 
[Figma](https://www.figma.com/design/1wiwltz5a0og0YIoKsuPmn/branch/jbPBoWxoSzvaJJ1Nzd1P7I/LSX-Tour-Operator-Design-System?node-id=8878-27845&node-type=FRAME&t=QgHiszKCmToUeDUK-0)

![welcom-page](https://github.com/user-attachments/assets/74cd69c6-fc40-495b-87b0-3ea66ec1bc9c)
