### ISSUE TITLE
2.0.0 - Itinerary Block

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/tour-operator#338]
### Description
We need to look at a way of pulling through the repeated itinerary content, which is then output according to the pattern applied.

### Tasks
- [x] Research the best way of inserting these itinerary.
- [x] Create a render_block function to replace a "Group" block filled with tags.
- [x] Map the available fields to output functions

### Block Variation
- [x] Try generate a group block variation which pre populates the css class name, as well as the post meta source.  It will use the meta-name  "itinerary-card".

### Legacy Functionality to be updated
- [x] Itinerary Description - Read More

### Screenshots
![Screenshot 2024-09-11 at 12 22 13](https://github.com/user-attachments/assets/6615cfc2-ddd9-4652-8207-0ff2445a92a3)
