### ISSUE TITLE
Tour Itinerary - Load More Days

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/tour-operator#339]
### Description
When you encounter a tour with  many individual itinerary , eg 18, the page can be quite large which will impact the loading speed.

### Solution
Shorten the itinerary to output only the first 3 items on page load, and have a JS function which triggers as soon as the page is loaded, which will fetch the rest of the itinerary items, to be displayed when the user clicks "read more".

### Tasks
- [ ] Edit the output function to only allow the first 3 items to output.
- [ ] Create a function to add the HTML output of the itinerary to the REST API post request.
- [ ] Create a JS function which triggers on "page loaded" to retrieve the additional itinerary items and populate the page.
- [ ] Edit the Show More function to trigger the itinerary retrieval as well.
