### ISSUE TITLE
Gallery Block for Accommodation and Destinations

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/tour-operator#342]
### Description
We need a gallery block which will pull through the ids and URLs stored in the "gallery" post meta field.

### Tasks
- [x] Register a block variation
- [x] Create a block_render function to call and populate the gallery fields.
- [x] Handle the Link attributes
- [x] Handle the cropping attributes
- [x] Handle the sizing attributes.

### Screenshots
![Screenshot 2024-09-16 at 09 32 49](https://github.com/user-attachments/assets/7e4b6b13-04ab-400f-b951-6792ade6acb9)
![Screenshot 2024-09-16 at 09 38 07](https://github.com/user-attachments/assets/073fecdb-cc9e-48df-a3e4-e84a7bbc160c)

**Comment by krugazul** [comment]
This issue can be closed, the sizing attributes are now handled by the block.  When assigning an image make sure the placeholder you use has the correct sizes generated.
