### ISSUE TITLE
Backend - Block Options - Sidebar Meta Panel with Custom Fields

### ISSUE THREAD

**Issue by ZaredRogers** [lightspeedwp/tour-operator#349]
### Description:
Generate a settings side panel in the block editor for the following Tour Operator (TO) fields. This panel should enhance user experience by moving custom fields and essential settings into the Block Options Sidebar.

#### General Settings:
- [x] Disable Singles (core + extensions)
- [x] Price
- [x] Single Supplement
- [x] Duration

#### Custom Fields (Move to Block Options Sidebar):
- **Spoken Languages:**
  - [x] Afrikaans
  - [x] English
  - [x] Xhosa
  - [x] Chinese
  - [x] Dutch
  - [x] Flemish
  - [x] French
  - [x] German
  - [x] Indian
  - [x] Italian
  - [x] Japanese
  - [x] Portuguese
  - [x] Russian
  - [x] Spanish
  - [x] Swahili
  - [x] Zulu

- **Special Interests:**
  - [x] Birding
  - [x] Cycling
  - [x] Gourmet
  - [x] etc.

- **Friendly:**
  - [x] Leisure
  - [x] Luxury
  - [x] Romance
  - [x] Weddings
  - [x] Business
  - [x] Children
  - [x] Disability
  - [x] Pet
  - [x] Vegetarian

- **Best Time to Visit:**
  - [x] Jan -> Dec (Dropdown)

- **Sticky Posts:**
  - [x] Sticky Tours
  - [x] Sticky Accommodation
  - [x] Sticky Destinations
  - [x] Convert these fields to use WordPress native sticky post functionality.

### Acceptance Criteria:
- [ ] Create a meta panel in the Block Options Sidebar.
- [ ] Ensure that all fields are editable within this sidebar.
- [ ] Group related fields for better user experience.
- [ ] Ensure compatibility with the block editor for easy integration.
- [ ] Move custom fields such as Spoken Languages, Special Interests, Friendly, Best Time to Visit, and Sticky posts to the sidebar.

### Additional Notes:
- The panel should be intuitive and responsive.
- Fields should have appropriate labels and tooltips for clarity.
- Make use of WordPress's native sticky post functionality where applicable.

**Comment by ZaredRogers** [comment]
This looks and works as expected
