### ISSUE TITLE
Tracking: List of new Tour Operator plugin blocks

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/tour-operator#356]
### Advanced Template Blocks

- [ ] TO Gallery Block - Tours, Destinations & Accommodation
- [ ] Tour - Single Template - Itinerary Block
- [ ] Tour - Single Template - Highlights Block 
- [ ] Accommodation - Single Template - Rooms/Units Block
- [ ] Destination - Single Country Template - Travel Info Block (electricity, visa variations) 

### Block Variations

- [ ] Custom Meta Field Blocks (e.g., price, duration, travel styles)
- [ ] Map Blocks (for WETU and Google integration)
- [ ] Related/Featured Blocks (tours, accommodations)
- [ ] Carousel Block Functionality (for galleries and connected content)

### Additional context

@ZaredRogers to add images to sub tasks
