### ISSUE TITLE
Tracking: Carousel Functionality

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/tour-operator#366]
- [ ] Create a block panel setting for the following blocks, to enable the carousel functionality.
- [ ] Add in the carousel JS functions to trigger the carousel in the frontend.
- [ ] Add in the carousel JS functions to trigger the carousel in the editor

- [ ] Single Tour 
  - Itinerary
  - Gallery
  - Related Tours

- [ ] Destination - Country
  - Gallery
  - Travel Info for Country
  - Regions
  - Connected Tours
  - Related destinations

- [ ] Destination - Region
  - Gallery
  - Connected Tours
  - Connected Accommodation
  - Related destinations

- [ ] Single Accommodation
  - Rooms
  - Gallery
  - Related Accommodation
