### ISSUE TITLE
Register Custom Block Category: `Tour Operator`

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/tour-operator#403]
## Description
This issue tracks the creation and registration of a custom block category called `Tour Operator` for the Tour Operator plugin. This custom category will group all relevant blocks together, enhancing their discoverability within the block editor.

Currently, the Tour Operator (TO) blocks are scattered throughout the Block Inserter. We need to organise these blocks under a single heading in the Block Inserter for improved user experience and easier access. Only selected blocks should display in the Block Editor, while template-related blocks should be shown in the Site Editor's Block Inserter.

### Requirements:

- [x] Create a new category in the Block Inserter for **Tour Operator** blocks.
   - All TO blocks should be grouped under this heading.
- [x] Display only selected blocks in the **Block Editor**.
   - Ensure that only relevant blocks appear when users are editing posts or pages.
- [x] Template-related blocks should be displayed in the **Site Editor’s Block Inserter**.

## Tasks
- [x] Decide on specific block categories that will be used within the Tour Operator plugin.
- [x] Ensure blocks are registered on the server side using the PHP function and `register_block_type` on the client side using the JavaScript function and on the client side using the JavaScript function`registerBlockType`.
- [x] Use metadata in the `block.json` file for each block, following the standard schema:
Here’s a code snippet for registering a custom pattern category for the Tour Operator Plugin using the register_block_pattern_category() function:

    ```json
    {
       "$schema": "https://schemas.wp.org/trunk/block.json",
       "apiVersion": 3,
       "name": "tour-operator/tour-collections",
       "title": "Tour Collections",
       "category": "tour-operator",
       "icon": "compass",
       "description": "Tour Operator content collections block for display tours, destinations and accommodation",
       "keywords": [ "accommodation", "tours", "destinations" ],
       "version": "1.0.0"
    }
    ```

## Acceptance Criteria
- [x] Depends on #401 
- [x] Custom block category `Tour Operator` is successfully registered and visible in the block inserter.
- [x] All related blocks are properly categorized under `Tour Operator`.
- [x] Custom category can be filtered and managed according to user needs.
- [x] All TO blocks are grouped under a single **Tour Operator** heading in the Block Inserter.
- [x] Only selected blocks are visible in the Block Editor.
- [x] Template-related blocks are visible in the Site Editor’s Block Inserter.

### Additional Notes:
- Ensure that the categorisation improves the user experience, making it easier for users to find and use the relevant blocks.

## References  
- [Registering custom block categories](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#managing-block-categories)
- [x] [`register_block_type`](https://developer.wordpress.org/reference/functions/register_block_type/) 
- [x] [`registerBlockType`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-blocks/#registerblocktype).
- [Managing block categories](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#managing-block-categories)
- [block_categories_all](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#block_categories_all)
- Before WordPress 5.8, this hook was known as block_categories, which is now deprecated. If you need to support older versions of WordPress, you might need a way to detect which filter should be used. You can check if block_categories is safe to use by seeing if the WP_Block_Editor_Context class exists, which was introduced in 5.8.
- It is possible to filter the list of default block categories using the block_categories_all filter. You can do it on the server by implementing a function which returns a list of categories. It is going to be used during block registration and to group blocks in the inserter. You can also use the second provided parameter $editor_context to filter the based on its content.
