### ISSUE TITLE
Backend - Site Editor - Patterns - Register Custom Pattern Category: `Tour Operator`

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/tour-operator#404]
**Description**  
This task involves creating a custom block pattern category for the Tour Operator Plugin using the `register_block_pattern_category()` function. The custom pattern category will help organize patterns for better usability within the block editor.

**References**  
- [Register Block Pattern Category Documentation](https://developer.wordpress.org/reference/functions/register_block_pattern_category/)

**Tasks**
- [x] Create a custom pattern category named `Tour Operator`.
- [x] Register the category using the `register_block_pattern_category()` function.
- [x] Ensure all relevant patterns are grouped under the new category.

**Code Snippets**
Here’s a code snippet for registering a custom pattern category for the Tour Operator Plugin using the register_block_pattern_category() function:

```
// Register a custom pattern category for the Tour Operator Plugin
function register_tour_operator_pattern_category() {
    if ( function_exists( 'register_block_pattern_category' ) ) {
        register_block_pattern_category(
            'tour-operator',
            array( 'label' => __( 'Tour Operator', 'tour-operator-plugin' ) )
        );
    }
}
add_action( 'init', 'register_tour_operator_pattern_category' );
```

This code registers a new pattern category called “Tour Operator,” making it available for organizing block patterns.

**Acceptance Criteria**
- [x] The custom pattern category `Tour Operator` is successfully registered.
- [x] All related block patterns appear under this category in the block editor.

**Comment by ashleyshaw** [comment]
### Default WordPress Pattern Categories

The default block pattern categories in WordPress include:

- **featured**
- **about**
- **audio** (added in WordPress 6.4)
- **banner**
- **buttons**
- **call-to-action**
- **columns**
- **contact**
- **footer**
- **gallery**
- **header**
- **media**
- **portfolio**
- **posts**
- **query** (use posts instead)
- **services**
- **team**
- **testimonials**
- **text**
- **video** (added in WordPress 6.4)

You can register custom categories using the `register_block_pattern_category()` function. For details, see the [documentation](https://developer.wordpress.org/reference/functions/register_block_pattern_category/).

**Comment by krugazul** [comment]
All patterns are included in the TO category by default when added to the plugin.
