### ISSUE TITLE
Register Custom Fields per Post Type using JSON

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/tour-operator#407]
### Description
Implement the registration of custom fields for each post type using [Create Content Model](https://github.com/Automattic/create-content-model/) in the Tour Operator Plugin. The custom field labels must be added to the block code for all block templates to improve data handling and display.

### Tasks
- [x] Register custom fields using JSON for all post types.
- [x] [Implement the CF labels](https://github.com/lightspeedwp/tour-operator/issues/424)

### Acceptance Criteria
- [x] All custom fields are correctly registered and display in the block templates.
